name: pi-cpu # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: pi cpu tool to show cpu and temp details # 79 char long summary
description: |
  This is pi-cpu, a simple optioned tool to show you live information about your Rasberry Pi's Board, Cpu and temperature.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  pi-cpu:
    plugin: make
    source-type: git
    source: https://github.com/Coraledev/pi-cpu
    override-pull: snapcraftctl pull

build-packages:
  - build-essential   

apps:
  pi-cpu:
    command: pi-cpu
assumes: [kernel-assets]
architectures:
  - build-on: arm64
    run-on: arm64
